'use client'

import { useState } from 'react'
import Link from 'next/link'
import { ArrowRight, Check, CheckCheck, Copy, Download, FileCheck2, FileText, LockKeyhole, RotateCcw, Search, ShieldCheck, TriangleAlert } from 'lucide-react'
import { toast } from 'sonner'
import { metadata, type DemoReport } from '@/lib/notrace-demo'
import { mapDemoFindings, mapDemoReport } from '@/lib/presentation/demo-mapper'
import { deriveReportCounts, type ReportViewModel } from '@/lib/presentation/models'
import { Input } from '@/components/ui/input'
import { usePrototype } from './provider'
import { EmptyState, GlassButton, GlassCard, Modal, MotionReveal, StatusBadge } from './primitives'

function textFor(report: ReportViewModel): string { const counts = deriveReportCounts(report); return `NOTRACE PRIVACY REPORT — ${report.provenance.toUpperCase()}\nFile: ${report.source.filename}\nFound: ${counts.found}\nRemoved: ${counts.removed}\nPreserved: ${counts.preserved}\nVerification: ${report.verification.state.toUpperCase()}` }
function exportReport(report: ReportViewModel): void { const url = URL.createObjectURL(new Blob([textFor(report)], { type: 'text/plain;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = `${report.source.filename.replace(/\.[^.]+$/, '')}_notrace_report.txt`; link.click(); link.remove(); URL.revokeObjectURL(url) }
async function copyReport(report: ReportViewModel) { try { await navigator.clipboard.writeText(textFor(report)); toast.success(`${report.provenance === 'demo' ? 'Simulated' : 'Local'} report copied to clipboard.`) } catch { toast.error('Clipboard access is unavailable. Use Export Report instead.') } }

export function DiffView({ report }: { report: ReportViewModel }) {
  const [showAll, setShowAll] = useState(false); const rows = showAll ? report.findingsBefore : report.findingsBefore.filter(finding => finding.status !== 'PROTECTED')
  return <GlassCard className="diff-panel"><div className="panel-heading"><div><span className="eyebrow">EVIDENCE</span><h2>A visible difference.</h2></div><button className="text-link" onClick={() => setShowAll(!showAll)}>{showAll ? 'Show findings only' : `Show all ${report.findingsBefore.length} findings`}</button></div><div className="diff-table"><div className="diff-header"><span>METADATA</span><span>VALUE</span><span /><span>STATUS</span></div>{rows.map(finding => <MotionReveal key={finding.id}><div className="diff-row"><strong>{finding.label}</strong><span className="before-value" title={finding.evidence || finding.explanation}>{finding.evidence || 'Unknown'}</span><ArrowRight size={14} /><StatusBadge tone={finding.status === 'REMOVABLE' ? 'success' : finding.status === 'PROTECTED' ? 'neutral' : 'warning'}>{finding.status}</StatusBadge></div></MotionReveal>)}</div></GlassCard>
}

export function VerificationPanel({ report }: { report: ReportViewModel }) { const incomplete = report.verification.state !== 'passed'; return <GlassCard className="verification-panel"><div className="verification-heading"><div className="verified-icon">{incomplete ? <TriangleAlert size={26} /> : <ShieldCheck size={26} />}</div><div><span className="eyebrow">{report.provenance === 'demo' ? 'SIMULATED VERIFICATION' : incomplete ? 'VERIFICATION INCOMPLETE' : 'VERIFICATION PASSED'}</span><h2>{incomplete ? 'A few things need a closer look.' : 'A clean result. Checked twice.'}</h2><p>{report.provenance === 'demo' ? 'Checks below are simulated, not real file validation.' : 'Checks below are derived from local independent verification.'}</p></div></div><div className="verification-list">{report.verification.checks.map(check => <p key={check.id}>{check.state === 'passed' ? <Check size={15} /> : <TriangleAlert size={15} />}{check.label}</p>)}</div>{report.verification.warnings.length > 0 && <div className="partial-warning"><TriangleAlert size={16} /><p>{report.verification.warnings.join(' ')}</p></div>}</GlassCard> }

export function ReportCard({ report }: { report: ReportViewModel }) { const counts = deriveReportCounts(report); return <GlassCard className="report-card"><div className="panel-heading"><div><span className="eyebrow">{report.provenance.toUpperCase()} SESSION REPORT</span><h2>NoTrace Privacy Report</h2><p className="report-filename">{report.source.filename}</p></div><div className="report-seal"><FileCheck2 size={27} /></div></div><div className="report-counts">{[['Found', counts.found], ['Removed', counts.removed], ['Requested', counts.requested], ['Preserved', counts.preserved]].map(([label, value]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><div className="report-risk"><div><span className="eyebrow">PRIVACY RISK · {report.provenance === 'demo' ? 'SIMULATED' : 'UNAVAILABLE'}</span><div className="risk-comparison"><span>— <small>{report.provenance === 'demo' ? 'SEE DEMO SCORE' : 'NOT AVAILABLE'}</small></span></div></div><StatusBadge tone={report.verification.state === 'passed' ? 'success' : 'warning'}>{report.verification.state === 'passed' ? 'Verification passed' : 'Verification incomplete'}</StatusBadge></div><div className="report-meta"><span>Provenance: {report.provenance}</span><span>{report.sessionOnly ? 'Session only' : 'Persistent'}</span></div><div className="action-row"><GlassButton onClick={() => copyReport(report)}><Copy data-icon="inline-start" />Copy Report</GlassButton><GlassButton onClick={() => { exportReport(report); toast.success('Report exported.') }}><Download data-icon="inline-start" />Export Report</GlassButton></div><p className="report-disclaimer">{report.provenance === 'demo' ? 'SIMULATED REPORT — no media was analyzed, changed, or verified.' : 'LOCAL REPORT — values are derived from local evidence.'}</p></GlassCard> }

export function OutputPanel({ report, onReset }: { report: ReportViewModel; onReset: () => void }) { const [modal, setModal] = useState(false); return <MotionReveal className="screen-stack" motionKey={report.source.filename}><GlassCard className="output-panel"><div className="output-icon"><CheckCheck size={34} /></div><StatusBadge tone={report.verification.state === 'passed' ? 'success' : 'warning'}>{report.verification.state === 'passed' ? 'PROCESS COMPLETE' : 'PROCESS COMPLETE · REVIEW'}</StatusBadge><h2>A little less shared.<br />A lot more yours.</h2><p className="privacy-note"><LockKeyhole size={13} />Your original remains untouched. Results are simulated.</p><div className="action-row"><GlassButton variant="default" onClick={() => setModal(true)}>Open Report</GlassButton><Link className="text-link" href="/reports">View Report<ArrowRight size={14} /></Link></div></GlassCard><ReportCard report={report} /><DiffView report={report} /><VerificationPanel report={report} /><div className="screen-actions"><GlassButton onClick={onReset}><RotateCcw data-icon="inline-start" />Try another policy</GlassButton></div><Modal open={modal} onOpenChange={setModal} title="Simulated output" description="No media file was created."><p>This demo produces a report only. Real downloads remain gated by verified provider-owned output.</p></Modal></MotionReveal> }

export function ReportsScreen() { const { reports, loadDemo } = usePrototype(); const [activeId, setActiveId] = useState(''); const [query, setQuery] = useState(''); const visible = reports.filter(r => `${r.filename} ${r.policy}`.toLowerCase().includes(query.toLowerCase())); const active = visible.find(r => r.id === activeId) || visible[0]; if (!reports.length) return <EmptyState title="No reports. No loose ends." description="Run a simulated cleanup or edit to see what changed. Your reports stay in this session and disappear on reload."><GlassButton variant="default" onClick={() => loadDemo()}>Start with a sample file<ArrowRight data-icon="inline-end" /></GlassButton></EmptyState>; const vm = active ? mapDemoReport(active, mapDemoFindings(metadata)) : undefined; return <div className="reports-layout"><aside className="reports-sidebar"><div className="metadata-search"><Search size={16} /><Input aria-label="Search reports" placeholder="Search reports…" value={query} onChange={e => setQuery(e.target.value)} /></div><div className="reports-list">{visible.map(report => <button key={report.id} className={`report-list-item ${report.id === active?.id ? 'report-active' : ''}`} onClick={() => setActiveId(report.id)} aria-pressed={report.id === active?.id}><FileText size={18} /><span><strong>{report.filename}</strong><small>{report.policy}</small></span>{report.partial ? <TriangleAlert size={14} /> : <Check size={14} />}</button>)}</div><p className="sidebar-note">{reports.length} simulated report{reports.length === 1 ? '' : 's'} in this session.<br />Reloading clears this history.</p></aside>{vm ? <MotionReveal key={active.id} motionKey={active.id} className="screen-stack"><ReportCard report={vm} /><DiffView report={vm} /><VerificationPanel report={vm} /></MotionReveal> : <EmptyState title="No matching reports" description="Try another file name or policy."><GlassButton onClick={() => setQuery('')}>Clear search</GlassButton></EmptyState>}</div> }
