'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowRight, Check, CheckCheck, Copy, Download, FileText, LockKeyhole, RotateCcw, Search, ShieldCheck, TriangleAlert } from 'lucide-react'
import { toast } from 'sonner'
import { metadata } from '@/lib/notrace-demo'
import { mapDemoFindings, mapDemoReport } from '@/lib/presentation/demo-mapper'
import { deriveReportCounts, type PrivacyFindingStatus, type ReportViewModel } from '@/lib/presentation/models'
import { Input } from '@/components/ui/input'
import { usePrototype } from './provider'
import { EmptyState, GlassButton, GlassCard, Modal, MotionReveal, StatusBadge } from './primitives'

function textFor(report: ReportViewModel): string { const counts = deriveReportCounts(report); return `NOTRACE PRIVACY REPORT — ${report.provenance.toUpperCase()}\nFile: ${report.source.filename}\nFound: ${counts.found}\nRemoved: ${counts.removed}\nPreserved: ${counts.preserved}\nVerification: ${report.verification.state.toUpperCase()}` }
function exportReport(report: ReportViewModel): void { const url = URL.createObjectURL(new Blob([textFor(report)], { type: 'text/plain;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = `${report.source.filename.replace(/\.[^.]+$/, '')}_notrace_report.txt`; link.click(); link.remove(); URL.revokeObjectURL(url) }
async function copyReport(report: ReportViewModel) { try { await navigator.clipboard.writeText(textFor(report)); toast.success(`${report.provenance === 'demo' ? 'Simulated' : 'Local'} report copied to clipboard.`) } catch { toast.error('Clipboard access is unavailable. Use Export Report instead.') } }

function toneFor(status: PrivacyFindingStatus) { return status === 'DETECTED' ? 'warning' as const : status === 'REMOVABLE' ? 'accent' as const : status === 'UNSUPPORTED' || status === 'UNKNOWN' ? 'warning' as const : status === 'PROTECTED' ? 'neutral' as const : 'neutral' as const }
function outcomeFor(report: ReportViewModel) {
  if (report.provenance === 'demo') return report.verification.state === 'passed' ? 'Simulated complete' : report.verification.state === 'failed' ? 'Simulated failed' : 'Simulated partial'
  if (report.verification.state === 'failed') return 'Failed'
  if (report.verification.state === 'cancelled') return 'Cancelled'
  if (report.requestedActions.length === 0) return 'Inspection only'
  if (report.verification.state === 'passed' && report.output?.downloadable) return 'Verified removal'
  return 'Removal review'
}
function provenanceLabel(report: ReportViewModel) { return report.provenance === 'demo' ? 'Simulated · Illustrative' : 'Local workflow · Evidence-backed' }
function FindingRows({ report }: { report: ReportViewModel }) { return <div className="report-evidence-list">{report.findingsBefore.length ? report.findingsBefore.map(finding => <div className="report-evidence-row" key={finding.id}><div><strong>{finding.label}</strong><small>{finding.category}{finding.evidence ? ` · ${finding.evidence}` : ''}</small></div><StatusBadge tone={toneFor(finding.status)}>{finding.status.replaceAll('_', ' ')}</StatusBadge></div>) : <p className="muted">No evidence findings were recorded.</p>}</div> }

export function DiffView({ report }: { report: ReportViewModel }) {
  const [showAll, setShowAll] = useState(false)
  const rows = showAll ? report.findingsBefore : report.findingsBefore.filter(finding => finding.status !== 'PROTECTED')
  return <section className="report-section diff-panel"><div className="report-section-heading"><div><span className="eyebrow">OBSERVED EVIDENCE</span><h2>What the record contains</h2></div>{report.findingsBefore.length > rows.length && <button className="text-link" onClick={() => setShowAll(!showAll)}>{showAll ? 'Show findings only' : `Show all ${report.findingsBefore.length} findings`}</button>}</div><div className="report-evidence-list">{rows.length ? rows.map(finding => <MotionReveal key={finding.id}><div className="report-evidence-row"><div><strong>{finding.label}</strong><small>{finding.category} · {finding.evidence || finding.explanation}</small></div><StatusBadge tone={toneFor(finding.status)}>{finding.status.replaceAll('_', ' ')}</StatusBadge></div></MotionReveal>) : <p className="muted">No evidence findings were recorded.</p>}</div></section>
}

export function VerificationPanel({ report }: { report: ReportViewModel }) {
  const passed = report.verification.state === 'passed'
  const demo = report.provenance === 'demo'
  return <section className={`report-section verification-panel report-verification-${report.verification.state}`} aria-labelledby="report-verification-title"><div className="verification-heading"><div className="verified-icon">{passed ? <ShieldCheck aria-hidden="true" size={24} /> : <TriangleAlert aria-hidden="true" size={24} />}</div><div><span className="eyebrow">{demo ? 'SIMULATED VERIFICATION' : 'VERIFICATION'}</span><h2 id="report-verification-title">{passed ? 'Independent checks passed' : report.verification.state === 'cancelled' ? 'Verification not run' : report.verification.state === 'failed' ? 'Verification failed' : 'Verification incomplete'}</h2><p>{demo ? 'Illustrative checks only. This report does not validate a real file.' : passed ? 'The recorded checks correspond to the approved workflow.' : 'No verified output is represented by this record.'}</p></div><StatusBadge tone={passed ? 'success' : demo ? 'demo' : 'warning'}>{report.verification.state}</StatusBadge></div><div className="verification-list">{report.verification.checks.map(check => <p key={check.id}>{check.state === 'passed' ? <Check aria-hidden="true" size={15} /> : <TriangleAlert aria-hidden="true" size={15} />}{check.label}<StatusBadge tone={check.state === 'passed' ? 'success' : 'warning'}>{check.state}</StatusBadge></p>)}</div>{report.verification.warnings.length > 0 && <div className="partial-warning"><TriangleAlert aria-hidden="true" size={16} /><p>{report.verification.warnings.join(' ')}</p></div>}</section>
}

export function ReportCard({ report }: { report: ReportViewModel }) {
  const counts = deriveReportCounts(report)
  const outcome = outcomeFor(report)
  const requested = report.requestedActions.length ? report.requestedActions : ['No removal requested']
  return <section className="report-record" aria-labelledby="report-record-title"><header className="report-record-header"><div><span className="eyebrow">SESSION EVIDENCE RECORD</span><h2 id="report-record-title">{report.source.filename}</h2><div className="report-record-meta"><span>{report.source.format || 'Format unavailable'}</span>{report.source.size !== undefined && <span>{report.source.size} bytes</span>}<StatusBadge tone={report.provenance === 'demo' ? 'demo' : 'accent'} kind="provenance">{provenanceLabel(report)}</StatusBadge></div></div><StatusBadge tone={outcome === 'Verified removal' ? 'success' : outcome === 'Failed' ? 'danger' : outcome === 'Cancelled' ? 'warning' : report.provenance === 'demo' ? 'demo' : 'neutral'}>{outcome}</StatusBadge></header><div className="report-record-flow"><section><span className="eyebrow">REQUESTED CHANGE</span><div className="report-action-list">{requested.map(action => <p key={action}>{action}</p>)}</div></section><section><span className="eyebrow">PERFORMED</span><div className="report-action-list">{report.actionsPerformed.length ? report.actionsPerformed.map(action => <p key={action}>{action}</p>) : <p className="muted">No change performed.</p>}</div></section><section><span className="eyebrow">OUTCOME</span><strong>{outcome}</strong><small>{report.sessionOnly ? 'Session-only record · local memory' : 'Record state'}</small></section></div><div className="report-supporting"><span>{counts.found} observed</span><span>{counts.requested} requested</span><span>{counts.removed} performed</span><span>{counts.preserved} preserved</span></div><div className="report-record-actions"><GlassButton onClick={() => copyReport(report)}><Copy data-icon="inline-start" />Copy Report</GlassButton><GlassButton onClick={() => { exportReport(report); toast.success('Report exported.') }}><Download data-icon="inline-start" />Export Report</GlassButton></div><p className="report-disclaimer">{report.provenance === 'demo' ? 'SIMULATED REPORT — illustrative data only.' : 'LOCAL REPORT — derived from local evidence and retained for this session.'}</p></section>
}

export function OutputPanel({ report, onReset }: { report: ReportViewModel; onReset: () => void }) { const [modal, setModal] = useState(false); return <MotionReveal className="screen-stack" motionKey={report.source.filename}><GlassCard className="output-panel"><div className="output-icon"><CheckCheck aria-hidden="true" size={34} /></div><StatusBadge tone={report.verification.state === 'passed' ? 'success' : 'warning'}>{report.verification.state === 'passed' ? 'PROCESS COMPLETE' : 'PROCESS COMPLETE · REVIEW'}</StatusBadge><h2>A little less shared.<br />A lot more yours.</h2><p className="privacy-note"><LockKeyhole aria-hidden="true" size={13} />Your original remains untouched. Results are simulated.</p><div className="action-row"><GlassButton variant="default" onClick={() => setModal(true)}>Open Report</GlassButton><Link className="text-link" href="/reports">View Report<ArrowRight aria-hidden="true" size={14} /></Link></div></GlassCard><ReportCard report={report} /><DiffView report={report} /><VerificationPanel report={report} /><div className="screen-actions"><GlassButton onClick={onReset}><RotateCcw data-icon="inline-start" />Try another policy</GlassButton></div><Modal open={modal} onOpenChange={setModal} title="Simulated output" description="No media file was created."><p>This demo produces a report only. Real downloads remain gated by verified provider-owned output.</p></Modal></MotionReveal> }

export function ReportsScreen() {
  const { reports, realReports, loadDemo } = usePrototype()
  const [activeId, setActiveId] = useState('')
  const [query, setQuery] = useState('')
  const visible = reports.filter(r => `${r.filename} ${r.policy}`.toLowerCase().includes(query.toLowerCase()))
  const visibleReal = realReports.filter(r => `${r.source.filename} local workflow ${r.verification.state}`.toLowerCase().includes(query.toLowerCase()))
  const allReports = [...visibleReal, ...visible.map(report => mapDemoReport(report, mapDemoFindings(metadata)))]
  const active = allReports.find(report => report.id === activeId) || allReports[0]
  useEffect(() => { if (activeId && !allReports.some(report => report.id === activeId)) setActiveId(allReports[0]?.id || '') }, [activeId, allReports.map(report => report.id).join('|')])
  if (!active && !reports.length && !realReports.length) return <EmptyState title="No session reports yet." description="Inspect a file to create an evidence record. Reports remain in this session and may clear when it reloads."><GlassButton variant="default" onClick={() => loadDemo()}>Start with a sample file<ArrowRight data-icon="inline-end" /></GlassButton></EmptyState>
  const list = [...visibleReal, ...visible.map(report => mapDemoReport(report, mapDemoFindings(metadata)))]
  return <div className="reports-archive"><header className="reports-route-header"><div><span className="eyebrow">REPORTS / SESSION EVIDENCE ARCHIVE</span><h2>Reports</h2><p>Open a local record to review its source, evidence, requested change, and outcome.</p></div><span className="reports-session-note">Session-only · local memory</span></header><div className="reports-layout"><aside className="reports-sidebar" aria-label="Session reports"><div className="metadata-search"><Search aria-hidden="true" size={16} /><Input aria-label="Search reports" placeholder="Search reports…" value={query} onChange={e => setQuery(e.target.value)} /></div><div className="reports-list">{list.map(report => { const outcome = outcomeFor(report); return <button key={report.id} className={`report-list-item ${report.id === active?.id ? 'report-active' : ''}`} onClick={() => setActiveId(report.id)} aria-pressed={report.id === active?.id} aria-label={`${report.source.filename}, ${provenanceLabel(report)}, ${outcome}`}><FileText aria-hidden="true" size={18} /><span><strong>{report.source.filename}</strong><small>{provenanceLabel(report)}</small><small>{outcome}</small></span>{outcome === 'Verified removal' || outcome === 'Simulated complete' ? <Check aria-hidden="true" size={14} /> : <TriangleAlert aria-hidden="true" size={14} />}</button> })}</div><p className="sidebar-note">{realReports.length ? `${realReports.length} local report${realReports.length === 1 ? '' : 's'}` : ''}{realReports.length && reports.length ? ' · ' : ''}{reports.length ? `${reports.length} simulated report${reports.length === 1 ? '' : 's'}` : ''}<br />Reloading clears this history.</p></aside>{active ? <MotionReveal key={active.id} motionKey={active.id} className="report-detail"><ReportCard report={active} /><DiffView report={active} /><VerificationPanel report={active} /></MotionReveal> : <EmptyState title="No matching reports" description="Try another file name or clear the search."><GlassButton onClick={() => setQuery('')}>Clear search</GlassButton></EmptyState>}</div></div>
}
