'use client'

import { useState } from 'react'
import { ArrowRight, BadgeCheck, Check, Fingerprint, FlaskConical, Info, ScanLine, ShieldCheck, Sparkles } from 'lucide-react'
import { toast } from 'sonner'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Field, FieldGroup, FieldLabel } from '@/components/ui/field'
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { GlassButton, GlassCard, Modal, StatusBadge } from './primitives'

type DetectionState = 'Detected' | 'Not detected' | 'Unknown' | 'Unsupported' | 'Supported'
export function WatermarkPanel() {
  const [state, setState] = useState<DetectionState>('Detected')
  const [credentials, setCredentials] = useState(true)
  const [modal, setModal] = useState<'remove' | 'experiment' | 'credentials' | 'verify' | null>(null)
  const [removeCredentials, setRemoveCredentials] = useState(false)
  const [removeSignal, setRemoveSignal] = useState(true)
  const [experimental, setExperimental] = useState(false)
  const tone = state === 'Detected' ? 'warning' : state === 'Not detected' ? 'success' : state === 'Supported' ? 'accent' : 'neutral'
  return <div className="screen-stack"><div className="watermark-intro"><span className="eyebrow">PROVENANCE / WATERMARK</span><h2>Represent provenance without overstating the signal.</h2><p>Content credentials tell a story about a file. Invisible watermarks embed a signal in it. We keep the two distinct.</p></div><div className="watermark-grid"><GlassCard className="watermark-card"><div className="watermark-card-top"><div className="icon-tile"><BadgeCheck size={26} /></div><StatusBadge tone={credentials ? 'warning' : 'success'}>{credentials ? 'Detected' : 'Not detected'}</StatusBadge></div><span className="eyebrow">PROVENANCE</span><h2>C2PA /<br />Content Credentials</h2><p>A signed record of origin and editing history, attached to a file.</p><dl><div><dt>Demo issuer</dt><dd>{credentials ? 'OpenAI' : '—'}</dd></div><div><dt>Mock signature</dt><dd>{credentials ? 'Present · not validated' : 'Not present'}</dd></div><div><dt>Capability</dt><dd>Simulated removal</dd></div></dl>{!credentials && <p className="success">No supported credentials detected in the demo result.</p>}<GlassButton onClick={() => setModal('credentials')}>View credentials<ArrowRight data-icon="inline-end" /></GlassButton></GlassCard><GlassCard className="watermark-card"><div className="watermark-card-top"><div className="icon-tile"><Fingerprint size={28} /></div><StatusBadge tone={tone}>{state}</StatusBadge></div><span className="eyebrow">EMBEDDED SIGNAL</span><h2>Invisible<br />Watermark</h2><p>A signal embedded in media, independent of its metadata or provenance.</p><dl><div><dt>Demo detector</dt><dd>Illustrative signal A</dd></div><div><dt>Result</dt><dd>{state}</dd></div><div><dt>Capability</dt><dd>{state === 'Unsupported' ? 'Unsupported' : state === 'Unknown' ? 'Unknown' : 'Demo support only'}</dd></div></dl><p className={state === 'Not detected' ? 'success watermark-state-note' : 'muted watermark-state-note'}>{state === 'Not detected' ? 'No supported watermark detected.' : state === 'Unknown' ? 'Insufficient information for a supported finding.' : state === 'Unsupported' ? 'No compatible detector in this demo scenario.' : state === 'Supported' ? 'A detector is available in this scenario. No detection result yet.' : 'Simulated signal detected. Not an analysis of your file.'}</p></GlassCard></div>
    <Alert className="watermark-caution"><Info /><AlertTitle>Detection has limits. Transparency matters.</AlertTitle><AlertDescription>No detector runs in this prototype. A “not detected” result does not establish the absence of a watermark. Changing provenance may invalidate signatures.</AlertDescription></Alert>
    <GlassCard className="watermark-controls"><FieldGroup><Field><FieldLabel htmlFor="signal-scenario">Explore a signal state</FieldLabel><Select value={state} onValueChange={v => { if (v) { setState(v as DetectionState); setExperimental(false) } }}><SelectTrigger id="signal-scenario"><SelectValue /></SelectTrigger><SelectContent><SelectGroup>{(['Detected','Not detected','Unknown','Unsupported','Supported'] as DetectionState[]).map(option => <SelectItem key={option} value={option}>{option}</SelectItem>)}</SelectGroup></SelectContent></Select></Field></FieldGroup><div className="action-row"><GlassButton disabled={!credentials && state !== 'Detected'} variant="default" onClick={() => setModal('remove')}><Sparkles data-icon="inline-start" />Remove Supported</GlassButton><GlassButton disabled={state !== 'Detected'} onClick={() => setModal('experiment')}><FlaskConical data-icon="inline-start" />Experimental Edit</GlassButton><GlassButton onClick={() => setModal('verify')}><ShieldCheck data-icon="inline-start" />Verify</GlassButton></div><p className="muted text-sm">Experimental operations are illustrative, limited, and never guaranteed.</p></GlassCard>
    <Modal open={modal !== null} onOpenChange={open => !open && setModal(null)} title={modal === 'remove' ? 'Choose the supported signals.' : modal === 'experiment' ? 'Experimental means uncertain.' : modal === 'credentials' ? 'Content credentials · demo' : 'Signal verification · simulated'} description={modal === 'remove' ? 'These are separate technologies. Select each explicitly. No actual processing will occur.' : modal === 'experiment' ? 'This demo illustrates an experimental watermark edit. Real-world reliability is unknown; removal is not guaranteed.' : modal === 'credentials' ? 'An illustrative provenance manifest, not extracted from or validated against your file.' : 'A presentation of the current demo state, not an independent verification.'}>
      {modal === 'remove' && <><FieldGroup><Field orientation="horizontal"><input className="native-checkbox" id="remove-c2pa" type="checkbox" disabled={!credentials} checked={removeCredentials} onChange={e => setRemoveCredentials(e.target.checked)} /><FieldLabel htmlFor="remove-c2pa">C2PA / Content Credentials</FieldLabel></Field><Field orientation="horizontal"><input className="native-checkbox" id="remove-signal" type="checkbox" disabled={state !== 'Detected'} checked={removeSignal} onChange={e => setRemoveSignal(e.target.checked)} /><FieldLabel htmlFor="remove-signal">Invisible watermark · demo signal A</FieldLabel></Field></FieldGroup><p className="muted">Removing credentials may remove provenance and invalidate the signature. It does not remove an invisible watermark.</p><GlassButton variant="default" disabled={!(removeCredentials && credentials) && !(removeSignal && state === 'Detected')} onClick={() => { if (removeCredentials) setCredentials(false); if (removeSignal && state === 'Detected') setState('Not detected'); setModal(null); toast.success('Demo signals updated. No file was changed.') }}>Simulate selected removal<ArrowRight data-icon="inline-end" /></GlassButton></>}
      {modal === 'experiment' && <><StatusBadge tone="warning">Experimental · not guaranteed</StatusBadge><p className="muted">The demo result will become “Unknown” to reflect an inconclusive signal after an experimental edit. Content credentials remain separate and unchanged.</p><GlassButton onClick={() => { setExperimental(true); setState('Unknown'); setModal(null); toast.warning('Experimental demo complete. Signal status is unknown.') }}><FlaskConical data-icon="inline-start" />Run experimental demo</GlassButton></>}
      {modal === 'credentials' && <div className="credential-manifest font-mono"><span>type: c2pa.manifest</span><span>issuer: {credentials ? 'OpenAI (illustrative)' : 'not detected'}</span><span>signature: not validated</span><span>assertions: created, edited</span><span>source: mocked demo data</span></div>}
      {modal === 'verify' && <><div className="verification-list"><p><Check />Provenance displayed independently</p><p><Check />Invisible signal state: {state}</p><p><Check />Original file untouched</p></div><StatusBadge tone={experimental || state === 'Unknown' || state === 'Unsupported' ? 'warning' : 'success'}>{experimental || state === 'Unknown' || state === 'Unsupported' ? 'Inconclusive demo result' : 'Demo state verified'}</StatusBadge><p className="muted">{state === 'Not detected' ? 'No supported watermark detected. Unsupported signals may still exist.' : 'This is not a real watermark or signature check.'}</p></>}
    </Modal></div>
}
